"""Initial migration

Revision ID: 46058affdbe2
Revises: 
Create Date: 2026-02-15 15:59:17.412984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46058affdbe2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('trial_ends_at', sa.DateTime(), nullable=False),
    sa.Column('is_pro', sa.Boolean(), nullable=False),
    sa.Column('payment_status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_business_id'), ['business_id'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    op.create_table('inventory_movement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('movement_type', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('stock_before', sa.Integer(), nullable=False),
    sa.Column('stock_after', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_movement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_movement_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_movement_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_movement_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_movement_user_id'), ['user_id'], unique=False)

    op.create_table('payment_proof',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=True),
    sa.Column('mime_type', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_proof', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_proof_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_proof_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_proof_user_id'), ['user_id'], unique=False)

    op.create_table('sale',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=150), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sale_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sale_created_at'))

    op.drop_table('sale')
    with op.batch_alter_table('payment_proof', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_proof_user_id'))
        batch_op.drop_index(batch_op.f('ix_payment_proof_created_at'))
        batch_op.drop_index(batch_op.f('ix_payment_proof_business_id'))

    op.drop_table('payment_proof')
    with op.batch_alter_table('inventory_movement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_movement_user_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_movement_product_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_movement_created_at'))
        batch_op.drop_index(batch_op.f('ix_inventory_movement_business_id'))

    op.drop_table('inventory_movement')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_business_id'))

    op.drop_table('product')
    op.drop_table('business')
    # ### end Alembic commands ###
